version: '3.7'

services:
  events_api:
    build: .
    # image: manning-airflow/events-api
    ports:
      - "5000:5000"
    networks:
      - mynetwork

networks:
  mynetwork:
    external:
      name: mynetwork